### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/zoo-notes#1]
## Setup Required

The Science Scribbler-based Zoo Notes app (or whatever this ends up getting called) needs to be deployed like a classic Custom Front End. Some setup is required.

- Proposed URL for CFE: **https://zoo-notes.zooniverse.org**
- This project uses React Scripts, similar to the [Alice Text Editor](https://github.com/zooniverse/text-editor) project
- There is an `npm run build` command that builds the code to `/build`
- The current target server of the deployment will be a `zooniverse-static` S3 bucket.
- NOTE: this CFE does not require Zooniverse authentication (logins) at the moment.

@shaunanoordin will perform the following:

- [x] add a `npm run publish` script that deploys the build files to the server/S3 bucket
- [x] create a `zoo-notes.zooniverse.org` directory in the `zooniverse-static` bucket

@camallen your help is requested for the following:

- [x] set up the routing rules for `zoo-notes.zooniverse.org` (similar to the Alice text editor, we're using `https://host.com/route` instead of `https://host.com/#/route`)
- [x] add `zoo-notes.zooniverse.org` to the Zooniverse DNS (https://github.com/zooniverse/operations/pull/495)

### Status

Required before 21 Sep 2020

**Comment by shaunanoordin** [comment]
- The `npm run deploy` script has been added by PR #3 
- Routing rules have been addressed by https://github.com/zooniverse/static/pull/184
- The `zoo-notes.zooniverse.org` is set by operations PR 495, but at the moment there seems to be an issue with one something in the pipeline (Terraform CI?) so that's a blocker to making those changes live.
  -  Note: I've already deployed the basic build to `zoo-notes.zooniverse.org` ; once this blocker is resolved we should see something at the URL.

**Comment by camallen** [comment]
DNS has been added - I believe this is all done.

**Comment by shaunanoordin** [comment]
Update: this IS all done! Should've closed this issue ages ago. Thanks Cam!

**Comment by eatyourgreens** [comment]
There's also a Jenkinsfile now, which runs the npm deploy script on merges to master.
